# Generated by Django 6.0.4 on 2026-04-26 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(default='Deluxe Room', max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('is_occupied', models.BooleanField(default=False)),
                ('ac_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('message', models.TextField()),
                ('meta_info', models.CharField(blank=True, max_length=200, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.room')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature_c', models.FloatField(default=22.0)),
                ('humidity_pct', models.FloatField(default=50.0)),
                ('co2_gas_ppm', models.IntegerField(default=400)),
                ('light_lux', models.IntegerField(default=300)),
                ('sound_db', models.FloatField(default=35.0)),
                ('motion_pir', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='dashboard.room')),
            ],
        ),
    ]
